services:
  postgres:
    image: postgres:16
    container_name: isa-cantora-postgres
    environment:
      POSTGRES_DB: isacantoradb
      POSTGRES_USER: isauser
      POSTGRES_PASSWORD: isapass
    ports:
      - "5433:5432" # porta externa 5433, interna continua 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U isauser -d isacantoradb"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: isa-cantora-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: isa-cantora-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/isacantoradb
      SPRING_DATASOURCE_USERNAME: isauser
      SPRING_DATASOURCE_PASSWORD: isapass
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
      JWT_SECRET: ${JWT_SECRET}
      MAIL_TO: ${MAIL_TO}
      MAIL_FROM: ${MAIL_FROM}
      SPRING_MAIL_HOST: ${MAIL_HOST}
      SPRING_MAIL_USERNAME: ${MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${MAIL_PASSWORD}
      ADMIN_USERNAME: ${ADMIN_USERNAME}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      CORS_ALLOWED_ORIGINS: ${CORS_ALLOWED_ORIGINS}
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  postgres_data:
  redis_data: