# application.properties (configurações comuns a todos os ambientes)
spring.application.name=artist-showcase-api
server.port=8080

spring.profiles.active=dev

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update