spring.application.name=artist-showcase-api
server.port=8080

# Banco H2 em memória
spring.datasource.url=jdbc:h2:mem:isacantoradb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate cria/atualiza as tabelas automaticamente
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Console web do H2 (acessível em /h2-console)
spring.h2.console.enabled=true